title: VAMPIRE Cookbook
description: A cookbook for VAMPIRE
theme: just-the-docs

url: https://Zikun-Yang.github.io/VAMPIRE_Cookbook

logo: "/assets/images/LOGO.png"

aux_links:
  Template Repository: https://github.com/Zikun-Yang/VAMPIRE_Cookbook
